// Generated by gencpp from file hsr_handing/face_info.msg
// DO NOT EDIT!


#ifndef HSR_HANDING_MESSAGE_FACE_INFO_H
#define HSR_HANDING_MESSAGE_FACE_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hsr_handing
{
template <class ContainerAllocator>
struct face_info_
{
  typedef face_info_<ContainerAllocator> Type;

  face_info_()
    : face_depth(0.0)
    , center_depth(0.0)
    , face_x(0.0)
    , face_y(0.0)
    , time(0.0)  {
    }
  face_info_(const ContainerAllocator& _alloc)
    : face_depth(0.0)
    , center_depth(0.0)
    , face_x(0.0)
    , face_y(0.0)
    , time(0.0)  {
  (void)_alloc;
    }



   typedef float _face_depth_type;
  _face_depth_type face_depth;

   typedef float _center_depth_type;
  _center_depth_type center_depth;

   typedef float _face_x_type;
  _face_x_type face_x;

   typedef float _face_y_type;
  _face_y_type face_y;

   typedef float _time_type;
  _time_type time;





  typedef boost::shared_ptr< ::hsr_handing::face_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hsr_handing::face_info_<ContainerAllocator> const> ConstPtr;

}; // struct face_info_

typedef ::hsr_handing::face_info_<std::allocator<void> > face_info;

typedef boost::shared_ptr< ::hsr_handing::face_info > face_infoPtr;
typedef boost::shared_ptr< ::hsr_handing::face_info const> face_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hsr_handing::face_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hsr_handing::face_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hsr_handing

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'hsr_handing': ['/home/naoyamada/CW/catkin_ws3/src/hsr_handing/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hsr_handing::face_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hsr_handing::face_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hsr_handing::face_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hsr_handing::face_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hsr_handing::face_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hsr_handing::face_info_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hsr_handing::face_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cb0496d5db40586ebe568131f126a11";
  }

  static const char* value(const ::hsr_handing::face_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cb0496d5db40586ULL;
  static const uint64_t static_value2 = 0xebe568131f126a11ULL;
};

template<class ContainerAllocator>
struct DataType< ::hsr_handing::face_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hsr_handing/face_info";
  }

  static const char* value(const ::hsr_handing::face_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hsr_handing::face_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 face_depth\n\
float32 center_depth\n\
float32 face_x\n\
float32 face_y\n\
float32 time\n\
";
  }

  static const char* value(const ::hsr_handing::face_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hsr_handing::face_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.face_depth);
      stream.next(m.center_depth);
      stream.next(m.face_x);
      stream.next(m.face_y);
      stream.next(m.time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct face_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hsr_handing::face_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hsr_handing::face_info_<ContainerAllocator>& v)
  {
    s << indent << "face_depth: ";
    Printer<float>::stream(s, indent + "  ", v.face_depth);
    s << indent << "center_depth: ";
    Printer<float>::stream(s, indent + "  ", v.center_depth);
    s << indent << "face_x: ";
    Printer<float>::stream(s, indent + "  ", v.face_x);
    s << indent << "face_y: ";
    Printer<float>::stream(s, indent + "  ", v.face_y);
    s << indent << "time: ";
    Printer<float>::stream(s, indent + "  ", v.time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HSR_HANDING_MESSAGE_FACE_INFO_H
