// Generated by gencpp from file hsr_handing/fuzzy.msg
// DO NOT EDIT!


#ifndef HSR_HANDING_MESSAGE_FUZZY_H
#define HSR_HANDING_MESSAGE_FUZZY_H

#include <ros/service_traits.h>


#include <hsr_handing/fuzzyRequest.h>
#include <hsr_handing/fuzzyResponse.h>


namespace hsr_handing
{

struct fuzzy
{

typedef fuzzyRequest Request;
typedef fuzzyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct fuzzy
} // namespace hsr_handing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hsr_handing::fuzzy > {
  static const char* value()
  {
    return "c8c38984a6ef7601852535eddb6b97ca";
  }

  static const char* value(const ::hsr_handing::fuzzy&) { return value(); }
};

template<>
struct DataType< ::hsr_handing::fuzzy > {
  static const char* value()
  {
    return "hsr_handing/fuzzy";
  }

  static const char* value(const ::hsr_handing::fuzzy&) { return value(); }
};


// service_traits::MD5Sum< ::hsr_handing::fuzzyRequest> should match 
// service_traits::MD5Sum< ::hsr_handing::fuzzy > 
template<>
struct MD5Sum< ::hsr_handing::fuzzyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hsr_handing::fuzzy >::value();
  }
  static const char* value(const ::hsr_handing::fuzzyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hsr_handing::fuzzyRequest> should match 
// service_traits::DataType< ::hsr_handing::fuzzy > 
template<>
struct DataType< ::hsr_handing::fuzzyRequest>
{
  static const char* value()
  {
    return DataType< ::hsr_handing::fuzzy >::value();
  }
  static const char* value(const ::hsr_handing::fuzzyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hsr_handing::fuzzyResponse> should match 
// service_traits::MD5Sum< ::hsr_handing::fuzzy > 
template<>
struct MD5Sum< ::hsr_handing::fuzzyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hsr_handing::fuzzy >::value();
  }
  static const char* value(const ::hsr_handing::fuzzyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hsr_handing::fuzzyResponse> should match 
// service_traits::DataType< ::hsr_handing::fuzzy > 
template<>
struct DataType< ::hsr_handing::fuzzyResponse>
{
  static const char* value()
  {
    return DataType< ::hsr_handing::fuzzy >::value();
  }
  static const char* value(const ::hsr_handing::fuzzyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HSR_HANDING_MESSAGE_FUZZY_H
