// Generated by gencpp from file hsr_handing/input4handing.msg
// DO NOT EDIT!


#ifndef HSR_HANDING_MESSAGE_INPUT4HANDING_H
#define HSR_HANDING_MESSAGE_INPUT4HANDING_H

#include <ros/service_traits.h>


#include <hsr_handing/input4handingRequest.h>
#include <hsr_handing/input4handingResponse.h>


namespace hsr_handing
{

struct input4handing
{

typedef input4handingRequest Request;
typedef input4handingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct input4handing
} // namespace hsr_handing


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hsr_handing::input4handing > {
  static const char* value()
  {
    return "7fe954f65abd774fd7fd0cc14c5c3b00";
  }

  static const char* value(const ::hsr_handing::input4handing&) { return value(); }
};

template<>
struct DataType< ::hsr_handing::input4handing > {
  static const char* value()
  {
    return "hsr_handing/input4handing";
  }

  static const char* value(const ::hsr_handing::input4handing&) { return value(); }
};


// service_traits::MD5Sum< ::hsr_handing::input4handingRequest> should match 
// service_traits::MD5Sum< ::hsr_handing::input4handing > 
template<>
struct MD5Sum< ::hsr_handing::input4handingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hsr_handing::input4handing >::value();
  }
  static const char* value(const ::hsr_handing::input4handingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hsr_handing::input4handingRequest> should match 
// service_traits::DataType< ::hsr_handing::input4handing > 
template<>
struct DataType< ::hsr_handing::input4handingRequest>
{
  static const char* value()
  {
    return DataType< ::hsr_handing::input4handing >::value();
  }
  static const char* value(const ::hsr_handing::input4handingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hsr_handing::input4handingResponse> should match 
// service_traits::MD5Sum< ::hsr_handing::input4handing > 
template<>
struct MD5Sum< ::hsr_handing::input4handingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hsr_handing::input4handing >::value();
  }
  static const char* value(const ::hsr_handing::input4handingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hsr_handing::input4handingResponse> should match 
// service_traits::DataType< ::hsr_handing::input4handing > 
template<>
struct DataType< ::hsr_handing::input4handingResponse>
{
  static const char* value()
  {
    return DataType< ::hsr_handing::input4handing >::value();
  }
  static const char* value(const ::hsr_handing::input4handingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HSR_HANDING_MESSAGE_INPUT4HANDING_H
