// Generated by gencpp from file key_controll/back_keyRequest.msg
// DO NOT EDIT!


#ifndef KEY_CONTROLL_MESSAGE_BACK_KEYREQUEST_H
#define KEY_CONTROLL_MESSAGE_BACK_KEYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace key_controll
{
template <class ContainerAllocator>
struct back_keyRequest_
{
  typedef back_keyRequest_<ContainerAllocator> Type;

  back_keyRequest_()
    : back_key()  {
    }
  back_keyRequest_(const ContainerAllocator& _alloc)
    : back_key(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _back_key_type;
  _back_key_type back_key;





  typedef boost::shared_ptr< ::key_controll::back_keyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::key_controll::back_keyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct back_keyRequest_

typedef ::key_controll::back_keyRequest_<std::allocator<void> > back_keyRequest;

typedef boost::shared_ptr< ::key_controll::back_keyRequest > back_keyRequestPtr;
typedef boost::shared_ptr< ::key_controll::back_keyRequest const> back_keyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::key_controll::back_keyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::key_controll::back_keyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace key_controll

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'key_controll': ['/home/naoyamada/CW/catkin_ws3/src/key_controll/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::key_controll::back_keyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::key_controll::back_keyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::key_controll::back_keyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::key_controll::back_keyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::key_controll::back_keyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::key_controll::back_keyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::key_controll::back_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "593c452cb0abe92dd91e6a781a2e3c66";
  }

  static const char* value(const ::key_controll::back_keyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x593c452cb0abe92dULL;
  static const uint64_t static_value2 = 0xd91e6a781a2e3c66ULL;
};

template<class ContainerAllocator>
struct DataType< ::key_controll::back_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "key_controll/back_keyRequest";
  }

  static const char* value(const ::key_controll::back_keyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::key_controll::back_keyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string  back_key\n\
";
  }

  static const char* value(const ::key_controll::back_keyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::key_controll::back_keyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.back_key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct back_keyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::key_controll::back_keyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::key_controll::back_keyRequest_<ContainerAllocator>& v)
  {
    s << indent << "back_key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.back_key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KEY_CONTROLL_MESSAGE_BACK_KEYREQUEST_H
