// Generated by gencpp from file key_controll/back_key.msg
// DO NOT EDIT!


#ifndef KEY_CONTROLL_MESSAGE_BACK_KEY_H
#define KEY_CONTROLL_MESSAGE_BACK_KEY_H

#include <ros/service_traits.h>


#include <key_controll/back_keyRequest.h>
#include <key_controll/back_keyResponse.h>


namespace key_controll
{

struct back_key
{

typedef back_keyRequest Request;
typedef back_keyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct back_key
} // namespace key_controll


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::key_controll::back_key > {
  static const char* value()
  {
    return "ec0067f1ae04091f857aa4aada8b0360";
  }

  static const char* value(const ::key_controll::back_key&) { return value(); }
};

template<>
struct DataType< ::key_controll::back_key > {
  static const char* value()
  {
    return "key_controll/back_key";
  }

  static const char* value(const ::key_controll::back_key&) { return value(); }
};


// service_traits::MD5Sum< ::key_controll::back_keyRequest> should match 
// service_traits::MD5Sum< ::key_controll::back_key > 
template<>
struct MD5Sum< ::key_controll::back_keyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::key_controll::back_key >::value();
  }
  static const char* value(const ::key_controll::back_keyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_controll::back_keyRequest> should match 
// service_traits::DataType< ::key_controll::back_key > 
template<>
struct DataType< ::key_controll::back_keyRequest>
{
  static const char* value()
  {
    return DataType< ::key_controll::back_key >::value();
  }
  static const char* value(const ::key_controll::back_keyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::key_controll::back_keyResponse> should match 
// service_traits::MD5Sum< ::key_controll::back_key > 
template<>
struct MD5Sum< ::key_controll::back_keyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::key_controll::back_key >::value();
  }
  static const char* value(const ::key_controll::back_keyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_controll::back_keyResponse> should match 
// service_traits::DataType< ::key_controll::back_key > 
template<>
struct DataType< ::key_controll::back_keyResponse>
{
  static const char* value()
  {
    return DataType< ::key_controll::back_key >::value();
  }
  static const char* value(const ::key_controll::back_keyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KEY_CONTROLL_MESSAGE_BACK_KEY_H
