// Generated by gencpp from file key_controll/right_key.msg
// DO NOT EDIT!


#ifndef KEY_CONTROLL_MESSAGE_RIGHT_KEY_H
#define KEY_CONTROLL_MESSAGE_RIGHT_KEY_H

#include <ros/service_traits.h>


#include <key_controll/right_keyRequest.h>
#include <key_controll/right_keyResponse.h>


namespace key_controll
{

struct right_key
{

typedef right_keyRequest Request;
typedef right_keyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct right_key
} // namespace key_controll


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::key_controll::right_key > {
  static const char* value()
  {
    return "d08d8dc0caa70812602fb3a50e31f337";
  }

  static const char* value(const ::key_controll::right_key&) { return value(); }
};

template<>
struct DataType< ::key_controll::right_key > {
  static const char* value()
  {
    return "key_controll/right_key";
  }

  static const char* value(const ::key_controll::right_key&) { return value(); }
};


// service_traits::MD5Sum< ::key_controll::right_keyRequest> should match 
// service_traits::MD5Sum< ::key_controll::right_key > 
template<>
struct MD5Sum< ::key_controll::right_keyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::key_controll::right_key >::value();
  }
  static const char* value(const ::key_controll::right_keyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_controll::right_keyRequest> should match 
// service_traits::DataType< ::key_controll::right_key > 
template<>
struct DataType< ::key_controll::right_keyRequest>
{
  static const char* value()
  {
    return DataType< ::key_controll::right_key >::value();
  }
  static const char* value(const ::key_controll::right_keyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::key_controll::right_keyResponse> should match 
// service_traits::MD5Sum< ::key_controll::right_key > 
template<>
struct MD5Sum< ::key_controll::right_keyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::key_controll::right_key >::value();
  }
  static const char* value(const ::key_controll::right_keyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_controll::right_keyResponse> should match 
// service_traits::DataType< ::key_controll::right_key > 
template<>
struct DataType< ::key_controll::right_keyResponse>
{
  static const char* value()
  {
    return DataType< ::key_controll::right_key >::value();
  }
  static const char* value(const ::key_controll::right_keyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KEY_CONTROLL_MESSAGE_RIGHT_KEY_H
