// Generated by gencpp from file key_controll/straight_key.msg
// DO NOT EDIT!


#ifndef KEY_CONTROLL_MESSAGE_STRAIGHT_KEY_H
#define KEY_CONTROLL_MESSAGE_STRAIGHT_KEY_H

#include <ros/service_traits.h>


#include <key_controll/straight_keyRequest.h>
#include <key_controll/straight_keyResponse.h>


namespace key_controll
{

struct straight_key
{

typedef straight_keyRequest Request;
typedef straight_keyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct straight_key
} // namespace key_controll


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::key_controll::straight_key > {
  static const char* value()
  {
    return "cbd8e12ce029666dd69311e278e5a145";
  }

  static const char* value(const ::key_controll::straight_key&) { return value(); }
};

template<>
struct DataType< ::key_controll::straight_key > {
  static const char* value()
  {
    return "key_controll/straight_key";
  }

  static const char* value(const ::key_controll::straight_key&) { return value(); }
};


// service_traits::MD5Sum< ::key_controll::straight_keyRequest> should match 
// service_traits::MD5Sum< ::key_controll::straight_key > 
template<>
struct MD5Sum< ::key_controll::straight_keyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::key_controll::straight_key >::value();
  }
  static const char* value(const ::key_controll::straight_keyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_controll::straight_keyRequest> should match 
// service_traits::DataType< ::key_controll::straight_key > 
template<>
struct DataType< ::key_controll::straight_keyRequest>
{
  static const char* value()
  {
    return DataType< ::key_controll::straight_key >::value();
  }
  static const char* value(const ::key_controll::straight_keyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::key_controll::straight_keyResponse> should match 
// service_traits::MD5Sum< ::key_controll::straight_key > 
template<>
struct MD5Sum< ::key_controll::straight_keyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::key_controll::straight_key >::value();
  }
  static const char* value(const ::key_controll::straight_keyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::key_controll::straight_keyResponse> should match 
// service_traits::DataType< ::key_controll::straight_key > 
template<>
struct DataType< ::key_controll::straight_keyResponse>
{
  static const char* value()
  {
    return DataType< ::key_controll::straight_key >::value();
  }
  static const char* value(const ::key_controll::straight_keyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KEY_CONTROLL_MESSAGE_STRAIGHT_KEY_H
