# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from hsr_handing/face_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class face_info(genpy.Message):
  _md5sum = "4cb0496d5db40586ebe568131f126a11"
  _type = "hsr_handing/face_info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 face_depth
float32 center_depth
float32 face_x
float32 face_y
float32 time
"""
  __slots__ = ['face_depth','center_depth','face_x','face_y','time']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       face_depth,center_depth,face_x,face_y,time

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(face_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.face_depth is None:
        self.face_depth = 0.
      if self.center_depth is None:
        self.center_depth = 0.
      if self.face_x is None:
        self.face_x = 0.
      if self.face_y is None:
        self.face_y = 0.
      if self.time is None:
        self.time = 0.
    else:
      self.face_depth = 0.
      self.center_depth = 0.
      self.face_x = 0.
      self.face_y = 0.
      self.time = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.face_depth, _x.center_depth, _x.face_x, _x.face_y, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.face_depth, _x.center_depth, _x.face_x, _x.face_y, _x.time,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.face_depth, _x.center_depth, _x.face_x, _x.face_y, _x.time))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.face_depth, _x.center_depth, _x.face_x, _x.face_y, _x.time,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
